bookings/urls.py
from django.urls import path
from .views import auth_views, apartment_views
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth import views as authentication_views
from django.urls import reverse_lazy


app_name = 'bookings'

urlpatterns = [
    path('', auth_views.home, name='home'),
    path('register/', auth_views.register, name='register'),
    path('login/', LoginView.as_view(template_name='bookings/login.html'), name='login'),
    path('logout/', auth_views.logout_request, name='logout'),
    # path('apartments/', apartment_views.apartments_view, name='apartments'),
    # path('apartments/<int:apartment_id>/', apartment_views.apartment_detail, name='apartment_detail'),
    path('contact/', apartment_views.contact, name='contact'),
    path('privacy-policy/', auth_views.privacy_policy, name='privacy_policy'),
    path('terms-and-conditions/', auth_views.terms_and_conditions, name='terms_and_conditions'),
    
    path('apartment/', apartment_views.book_apartment, name='book_apartment'),
    path('booking-success/', apartment_views.booking_success, name='booking_success'),
    path('booking-failed/', apartment_views.booking_failed, name='booking_failed'),
    path('pricings/', apartment_views.display_pricings, name='display_pricings'),
    # path('test/' ,apartment_views.test_page, name='test_page'),

    #availability

    path('check_availability/', apartment_views.check_availability, name='check_availability'),
    # path('availability_result/<str:available>/', apartment_views.availability_result, name='availability_result'),

    #Profile urls
    path('profile/', auth_views.profile_view, name='profile'),
    path('profile/delete', auth_views.delete_account, name='delete_account'),
    path('password_change/', PasswordChangeView.as_view(template_name='bookings/password_change.html',success_url=reverse_lazy('bookings:password_change_done')), name='password_change'),


    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),
    #Password reset links
    path('password-reset/', authentication_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html',
        success_url=reverse_lazy('bookings:password_reset_done'),
        email_template_name='registration/password_reset_email.html'
    ), name='password_reset'),

    path('password-reset/done/', authentication_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', authentication_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url=reverse_lazy('bookings:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset_complete/', authentication_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),

    #payment urls
    path('start-payment/', apartment_views.start_payment, name='start_payment'),
    path('stripe/webhook/', apartment_views.StripeWebhook.as_view(), name='stripe_webhook'),

    #canceling booking urls
    path('booking/cancel/<int:booking_id>/', apartment_views.cancel_booking, name='cancel_booking'),

    #Bookings
    path('display-bookings/', apartment_views.display_bookings, name='display_bookings'),
]

hotelapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookings.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'bookings.views.error_views.custom_404_view'
handler500 = 'bookings.views.error_views.custom_500_view'

bookings/views/apartment_views.py
import uuid
from django.shortcuts import get_object_or_404, render, redirect
from bookings.forms import BookingForm, AvailabilityCheckForm
from ..models import Apartment, Booking, User
from datetime import date, timedelta, datetime
from django.db.models import Q
from django.contrib import messages
from django.db import transaction
from django.http import JsonResponse
import stripe
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.views import View
import json
import logging
from django.template.loader import render_to_string
from django.core.mail import send_mail


logger = logging.getLogger(__name__)




# def apartments_view(request):
#     if request.method == "GET":
#         context = fetch_appartments(request)
        
#         return render(request, 'bookings/available_apartments.html', context)
    

    
def book_apartment(request):
    apartment = get_object_or_404(Apartment)
    
    #Check user authentication
    if not request.user.is_authenticated:
        messages.info(request, 'Please login to make a booking. Showing availability only.', extra_tags='no_swal')
    if request.method == "POST":
        form = BookingForm(request.POST)
        if form.is_valid():
            check_in_date = form.cleaned_data['check_in_date']
            check_out_date = form.cleaned_data['check_out_date']
            number_of_adults = form.cleaned_data['number_of_adults']
            number_of_kids = form.cleaned_data['number_of_kids'] or 0

            
            # check if the apartment is already booked
            overlapping_bookings = Booking.objects.filter(
                check_in_date__lt=check_out_date, 
                check_out_date__gt=check_in_date,
                status='confirmed'
            )

            if overlapping_bookings.exists():
                messages.error(request, 'The apartment is already booked for the specified date.')
            else:
                request.session['temp_booking'] = {
                    'apartment_id':apartment.id,
                    'user_id': request.user.id,
                    'check_in_date': check_in_date.strftime('%Y-%m-%d'),
                    'check_out_date': check_out_date.strftime('%Y-%m-%d'),
                    'number_of_adults': number_of_adults,
                    'number_of_kids': number_of_kids,
                    'total_price': str(calculate_price(apartment, check_in_date, check_out_date))
                }
                return redirect('bookings:start_payment')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, error)
    else:
        form = BookingForm()
        
    context = {'form': form, 'apartment': apartment}
    return render(request, 'bookings/apartment.html', context)




def check_availability(request):
    apartment = get_object_or_404(Apartment)

    if request.method == "POST":
        form = AvailabilityCheckForm(request.POST)
        if form.is_valid():
            check_in_date = form.cleaned_data['check_in_date']
            check_out_date = form.cleaned_data['check_out_date']

            overlapping_bookings = Booking.objects.filter(
                check_in_date__lt=check_out_date, check_out_date__gt=check_in_date
            )

            if overlapping_bookings.exists():
                messages.error(request, 'The apartment is not available for the specified dates.')

            else:
                messages.success(request, 'The apartment is available for the specified dates, you can book the apartment by signing up.')

            return redirect('bookings:check_availability')
        
        else:

            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, error)
    else:
        form = AvailabilityCheckForm()


    context = {'form': form, 'apartment': apartment}
    return render(request, 'bookings/test.html', context)

        


def booking_success(request):
    return render(request, 'bookings/booking_success.html')

def booking_failed(request):
    return render(request, 'bookings/booking_failed.html')

def display_bookings(request):
    bookings = Booking.objects.filter(user=request.user)
    return render(request, 'bookings/display_bookings.html', {'bookings': bookings})

def display_pricings(request):
    apartments = Apartment.objects.prefetch_related('monthly_prices').all()
    return render(request, 'bookings/pricing_list.html', {'apartments': apartments})


# def apartment_detail(request, apartment_id):
#     apartment = get_object_or_404(Apartment, id=apartment_id)
#     context = {'apartment': apartment}
#     return render(request, 'bookings/apartment_detail.html', context)



# def fetch_appartments(request, items_per_page=10):
#     context = {}
    
#     sort_order = request.GET.get('sort', 'asc') # Default to ascending
    
#     if sort_order == 'asc':
#         apartments_list = Apartment.objects.all().order_by('price_per_night')
#     else:
#         apartments_list = Apartment.objects.all().order_by('-price_per_night')
    
#     paginator = Paginator(apartments_list, items_per_page)
#     page = request.GET.get('page')
#     apartments = paginator.get_page(page)
    
#     context['apartments'] = apartments
#     return context



def calculate_price(apartment, check_in_date, check_out_date):
    
    monthly_price = apartment.monthly_prices.get(month=check_in_date.month)

    days = (check_out_date - check_in_date).days
    return monthly_price.price * days



def apartment_availability(request):
    
    #Get all bookings
    bookings = Booking.objects.all()
    
    #Dictionaries to hold bookings and availability
    booked_dates = {}
    available_dates = {}
    
    
    #Check every day for the next 30 days
    for day in (date.today() + timedelta(n) for n in range(30)):
        booked_apartments = [b.apartment for b in bookings if b.check_in_date <= day <= b.check_out_date]
        available_apartments = Apartment.objects.exclude(id__in=[a.id for a in booked_apartments])
        
        booked_dates[day] = booked_apartments
        available_dates[day] = available_apartments
        
    return render(request, 'path_to_template.html', {
        'booked_dates': booked_dates,
        'available_dates': available_dates,
    })



def send_custom_email(subject, message, to_email_list, from_email=None):
    """
    Sends an email using the Django send_mail function with the Mailjet backend.

    Args:
    - subject (str): Subject of the email.
    - message (str): Plain text body of the email.
    - to_email_list (list): List of recipient email addresses.
    - from_email (str, optional): Sender's email address. Defaults to the DEFAULT_FROM_EMAIL setting.

    Returns:
    - int: Number of successfully sent emails.
    """
    
    # Use the default from_email if none provided
    if not from_email:
        from django.conf import settings
        from_email = settings.DEFAULT_FROM_EMAIL

    # Send the email
    return send_mail(subject, message, from_email, to_email_list)

def send_owner_email(subject, message):
    # if not from_email:
    #     from django.conf import settings
    #     from_email = settings.DEFAULT_FROM_EMAIL

    send_mail(subject, message, 'saricstay@gmail.com', ['dankovicmarko18@gmail.com'])



def contact(request):
    if request.method == "POST":
        message_name = request.POST['message_name']
        message_email = request.POST['message_email']
        message = request.POST['message']
        subject = "Message from {}: {}".format(message_name, message_email)
        #send an email
        send_mail(
            subject,
            message,
            'saricstay@gmail.com',  # Ensure this is the corrected variable name
            ['saricstay@gmail.com'],
        )

        
        messages.success(request, "Thank you for contacting us {message_name}! We'll get back to you shortly.")


    return render(request, 'bookings/contact.html')


def start_payment(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY
    idempotency_key = str(uuid.uuid4())
    temp_booking = request.session.get('temp_booking')
    if not temp_booking:
        return redirect('bookings:book_apartment') # Redirect back if no temp booking in session
    
    # Create a Checkout Session
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price_data': {
                'currency': 'eur',
                'product_data': {
                    'name': 'Apartment Booking',
                },
                'unit_amount': int(float(temp_booking['total_price']) * 100),
            },
            'quantity': 1,
        }],
        mode='payment',
        success_url=request.build_absolute_uri(reverse('bookings:booking_success')),
        cancel_url=request.build_absolute_uri(reverse('bookings:book_apartment')),
        metadata={'temp_booking': json.dumps(temp_booking), 'idempotency_key': idempotency_key},
    )
    
    return redirect(session.url)


class StripeWebhook(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(StripeWebhook, self).dispatch(*args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        payload = request.body
        sig_header = request.META['HTTP_STRIPE_SIGNATURE']
        endpoint_secret = 'whsec_c3f099f10c9202c2b15aeae868eb575dc8c0a6e990892fa5970590f7ba3aecf0'

        try:
            event = stripe.Webhook.construct_event(
                payload, sig_header, endpoint_secret
            )

            
        except ValueError:
            #Invalid payload
            return JsonResponse({'status': 'error', 'message': 'Invalid payload'}, status=400)

bookings/views/auth_views.py
from venv import logger
from django.shortcuts import render, redirect
from ..models import Apartment, User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
import logging
from django.contrib.messages import error, success
from django.contrib.auth.decorators import login_required
from bookings.forms import ProfileForm
from django.contrib import messages


def home(request):
    return render(request, 'bookings/home.html')



def login_request(request):
    #If user is already authenticated, redirect them to the home page
    if request.user_isauthenticated:
        return redirect('bookings:home')
    
    #Instantiate the form
    form = AuthenticationForm(request, data=request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            #Form data is valid
            user = form.get_user()
            login(request, user)
            return redirect('bookings:home')
        else:
            #Display form with errors
            error(request, "Invalid username or password.")



def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST or None)
        context = {'form': form}
        if form.is_valid():
            user = form.save()

            #Set the backend attribute
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            #Log the user in
            login(request, user)
            success(request, "Registration succesful!")
            return redirect('bookings:home')
        else:
            #If the form is not valid, return the form along with the validation error
            error(request, "Registratio failed. Please check the form for errors.")
            return render(request, 'bookings/register.html', context)
    else:
        form = UserCreationForm()
        return render(request, 'bookings/register.html', {'form': form})


def logout_request(request):
    logout(request)
    return redirect('bookings:home')


@login_required
def profile_view(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            success(request, 'Your profile has been updated!')
            return redirect('bookings:profile')
    else:
        form = ProfileForm(instance=request.user)
    
    return render(request, 'bookings/profile.html', {'form': form})

def delete_account(request):
    if request.method == "POST":
        user = request.user
        user.delete() #This deletes the user from database
        messages.success(request, "Your account has been succesfully deleted.")
        logout(request) #Log the user out
        return redirect('bookings:home')
    return render(request, 'bookings/confirm_delete.html')



#Views for rendering the Privacy and Policy page, and Terms & Conditions pages
def privacy_policy(request):
    return render(request, 'bookings/privacy_policy.html')

def terms_and_conditions(request):
    return render(request, 'bookings/terms_and_conditions.html')

bookings/views/error_views.py
from django.shortcuts import render

def custom_404_view(request, exception):
    return render(request, 'errors/404.html', {}, status=404)

def custom_500_view(request):
    return render(request, 'errors/500.html', {}, status=500)

bookings/templates/bookings/apartment_detail.html
{% extends "bookings/base.html" %}

{% block content %}

<div class="container mt-5">
    <!-- Carousel -->
    <div id="apartmentImagesCarousel" class="carousel slide" data-ride="carousel">

        <!-- Indicators or Dots -->
        <ol class="carousel-indicators">
            {% for image in apartment.images.all %}
                <li data-target="#apartmentImagesCarousel" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
            {% endfor %}
        </ol>

        <!-- Slides -->
        <div class="carousel-inner">
            {% for image in apartment.images.all %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <img src="{{ image.image.url }}" class="d-block w-100" alt="{{ apartment.first_name }} image">
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- End of Carousel -->

    <div class="mt-4">
        <h1>{{ apartment.name }}</h1>
        <p class="text-muted"><strong>Price Per Night:</strong> ${{ apartment.price_per_night }}</p>
        <p><strong>Description:</strong></p>
        <p class="lead">{{ apartment.description }}</p>

        <!-- Book Now Button -->
        {% if user.is_authenticated %}
            <div class="mt-3">
                <button class="btn btn-success btn-lg">Book now</button>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

bookings/templates/bookings/availability_result.html
{% extends "bookings/base.html" %}

{% block content %}
<div class="container mt-5">
    {% if available == 'True' %}
        <h3>The apartment is available for your selected dates!</h3>
    {% else %}
        <h3>Sorry, the apartment is not available for your selected dates.</h3>
    {% endif %}
</div>
{% endblock %}

bookings/templates/bookings/available_apartments.html
{% extends "bookings/base.html" %}

{% block content %}
<div class="container my-4 ">
    <div class="row">
        
    </div>
    <!-- Sorting Section -->
    <div class="row mb-3">
        <div class="col-12 d-flex justify-content-start">
            <a href="?sort=asc" class="btn btn-light mr-2">Sort by Price: Low to High</a>
            <a href="?sort=desc" class="btn btn-light">Sort by Price: High to Low</a>
        </div>
    </div>

    <!-- Apartments Display Section -->
    <div class="row">
        {% for apartment in apartments %}
            <div class="col-md-4 mb-4">
                <div class="card h-100">
                    <img src="{{ apartment.image.url }}" class="card-img-top" alt="{{ apartment.name }}">
                    <div class="card-body">
                        <h4 class="card-title">{{ apartment.name }}</h4>
                        <p class="card-text">Price: ${{ apartment.price_per_night }}</p>
                        <a href="{% url 'bookings:apartment_detail' apartment.id %}" class="btn btn-primary">View Apartment</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <div class="pagination">
                <span class="step-links">
                    {% if apartments.has_previous %}
                        <a href="?page=1" class="btn btn-light">&laquo; previous</a>
                    {% endif %}
            
                    <span class="current mx-3">
                        Page {{ apartments.number }} of {{ apartments.paginator.num_pages }}.
                    </span>
            
                    {% if apartments.has_next %}
                        <a href="?page={{ apartments.next_page_number }}" class="btn btn-light">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookings/templates/bookings/booking_success.html
<!-- bookings/templates/bookings/booking_success.html -->
{% extends "bookings/base.html" %}
{% load static %}


{% block content %}
<div class="container" style="padding-top: 80px; padding-bottom: 280px;">
    <h1>Booking Successful!</h1>
    <p>Thank you for booking with us. We've reserved the apartment for your selected dates.</p>
    <a href="{% url 'bookings:home' %}">Return to Apartments</a>
</div>



{% endblock %}

bookings/templates/bookings/contact.html
{% extends "bookings/base.html" %}

{% block content %}
<div id="content-wrap" style="padding-top: 50px;">
    <div class="container flex-container my-4 mt-5" style=" font-family: 'Roboto', sans-serif;">
        <h1 class="mb-5">Contact Us</h1>
        


        <div class="row mb-5">
            <!-- Address -->
            <div class="col-md-4">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="min-height: 200px;">
                    <h4 class="card-title">Address:</h4>
                    <p class="card-text">Eugena Tomica 22</p>
                    <p class="card-text">23000 Zadar</p>
                </div>
            </div>
            
            <!-- Phone Numbers -->
            <div class="col-md-4">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="min-height: 200px;">
                    <h4 class="card-title">Phone:</h4>
                    <p class="card-text"><a href="tel:+385916210853" class="text-decoration-none text-dark">+385916210853</a></p>
                    <p class="card-text"><a href="tel:+385996575425" class="text-decoration-none text-dark">+385996575425</a></p>
                </div>
            </div>
            
            <!-- Email -->
            <div class="col-md-4">
                <div class="card shadow-lg p-3 mb-5 bg-white rounded" style="min-height: 200px;">
                    <h4 class="card-title">Email:</h4>
                    <p class="card-text"><a href="mailto:e-mail.gverduk@gmail.com" class="text-decoration-none text-dark">saricstay@gmail.com</a></p>
                    <p class="card-text"><a href="mailto:e-mail.gverduk@gmail.com" class="text-decoration-none text-dark">e-mail.gverduk@gmail.com</a></p>
                </div>
            </div>
        </div>

        <div class="container my-5 shadow-lg p-3 mb-5 bg-white rounded">
            <h2 class="text-center mb-4">Leave a Message</h2>
            <form action="{% url 'bookings:contact' %}" method="post" id="messageForm">
                <!-- CSRF token for Django -->
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Your Name:</label>
                    <input type="text" class="form-control" id="message_name" name="message_name" required>
                </div>
                <div class="form-group">
                    <label for="email">Your Email:</label>
                    <input type="email" class="form-control" id="message_email" name="message_email" required>
                </div>
        
                <div class="form-group">
                    <label for="message">Message:</label>
                    <textarea class="form-control" id="message" name="message" rows="4" required></textarea>
                </div>
        
                <button type="submit" class="btn dento-btn mx-2" data-animation="fadeInDown" data-delay="500ms">Send</button>
            </form>
            {% if messages %}
                {% for message in messages %}

                    <script>
                        Swal.fire({
                            title: '',
                            text: '{{ message }}',
                            icon: 'success',
                            confirmButtonText: 'Ok'
                        })
                    </script>

                {% endfor %}
            {% endif %}
        </div>
        

        <!-- Google Maps Embed -->
        <h2 class="mt-5 mb-4">Find Us On Map</h2>
        <div class="shadow p-3 mb-5 bg-white rounded" style="width: 100%; height: 400px;">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2950.691570986325!2d15.237108615656568!3d44.106658079098084!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4761faf538fc803f%3A0x13ae80c1b07add8a!2sEugena%20Tomi%C4%87a%2022%2C%2023000%2C%20Zadar%2C%20Croatia!5e0!3m2!1sen!2sus!4v1633533571567!5m2!1sen!2sus" loading="lazy" allowfullscreen="" aria-hidden="false" tabindex="0" style="border:0; width: 100%; height: 100%;"></iframe>
        </div>
    </div>
</div>  {# end of content-wrap #}
{% endblock %}

bookings/templates/bookings/home.html
<body>
{% extends "bookings/base.html" %}
{% load static %}
{% block content %}
<section class="welcome-area">
      <!-- Single Welcome Slide -->
      <div class="welcome-welcome-slide bg-img bg-gradient-overlay jarallax" style="background-image: url({% static '/bookings/img/wallpaperflare.com_wallpaper.jpg' %});">
        <div class="container h-100"> 
          <div class="row h-100 align-items-center">
            <div class="col-12">
              <!-- Welcome Text -->
              <div class="welcome-text text-center">
                <h2 data-animation="fadeInDown" data-delay="100ms">Experience Comfort Away From Your Home in The Hearth Of Zadar</h2>
                <p data-animation="fadeInDown" data-delay="300ms">Discover the charm of Zadar with a comfortable stay at our apartment. We believe in offering a warm and inviting space that feels just like home.</p>
                <div class="welcome-btn-group">
                  <a href="{% url 'bookings:book_apartment' %}" class="btn dento-btn mx-2" data-animation="fadeInDown" data-delay="500ms">Book Now</a>
                  <a href="{% url 'bookings:contact' %}" class="btn dento-btn mx-2 active" data-animation="fadeInDown" data-delay="700ms">Contact Us</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}
</body>
</html>

bookings/templates/bookings/profile.html
{% extends "bookings/base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" href="{% static 'styles.css' %}">


<div class="container mt-5" style="padding-top: 50px; padding-bottom: 100px;">
    <div class="row">
        <div class="col-md-6">
            <h2>Your Profile</h2>
            <form method="post" action="{% url 'bookings:profile' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label class="form-label">Username</label>
                    <input type="text" class="form-control" name="{{ form.username.name }}" value="{{ user.username }}" readonly>
                    <small class="text-muted">You cannot change your username.</small>
                </div>
                <!-- Other Fields -->
                <div class="mb-3">
                    <label class="form-label">First Name</label>
                    <input type="text" class="form-control" name="{{ form.first_name.name }}" value="{{ user.first_name }}">
                </div>
                <div class="mb-3">
                    <label class="form-label">Last Name</label>
                    <input type="text" class="form-control" name="{{ form.last_name.name }}" value="{{ user.last_name }}">
                </div>
                <div class="mb-3">
                    <label class="form-label">Email</label>
                    <input type="email" class="form-control" name="{{ form.email.name }}" value="{{ user.email }}">
                </div>

                <a class="d-block mt-2">
                    <a href="{% url 'bookings:password_change' %}">Reset Password</a>
                </a>

                <button type="submit" class="btn btn-primary">Update Profile</button>

                <a href="{% url 'bookings:delete_account' %}" class="btn btn-danger">Delete Account</a>

            </form>
        </div>
    </div>
</div>


{% endblock %}

bookings/templates/bookings/register.html
{% extends "bookings/base.html" %}

{% block content %}


    <div class="container mt-5 justify-content-center col-md-6" style="padding-top: 80px; padding-bottom: 80px;">
        <form action="{% url 'bookings:register' %}" method="post" class="p-3 rounded bg-light">
            <h1>SignUp</h1>
            <hr>
            {% csrf_token %}

            <!-- Display form errors (if any) -->
            {% if form.errors %}
                <div class="alert alert-danger">
                    Please correct the errors below.
                </div>
            {% endif %}
            <!-- Custom fields (if you have any extra fields in your user model) -->
            <div class="mb-3">
                <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                <input type="text" name="{{ form.username.name }}" id="{{ form.username.auto_id }}" class="form-control" placeholder="Enter username" required>
            </div>

            <div class="mb-3">
                <label for="{{ form.email.id_for_label}}" class="form-label">Email</label>
                <input type="email" name="{{ form.email.name }}" id="{{ form.email.auto_id }}" class="form-control" placeholder="Enter Email" required>
            </div>

            <div class="mb-3">
                <label for="firstname" class="form-label">First Name</label>
                <input type="text" class="form-control" placeholder="Enter First Name" name="firstname" required>
            </div>

            <div class="mb-3">
                <label for="lastname" class="form-label">Last Name</label>
                <input type="text" class="form-control" placeholder="Enter Last Name" name="lastname" required>
            </div>

            <div class="mb-3">
                <label for="{{ form.password1.id_for_label }}" class="form-label">Password</label>
                <input type="password" name="{{ form.password1.name }}" id="{{ form.password1.auto_id }}" class="form-control" placeholder="Enter password" required>
            </div>
            <div class="mb-3">
                <label for="{{ form.password2.id_for_label }}" class="form-label">Repeat password</label>
                <input type="password" name="{{ form.password2.name }}" id="{{ form.password2.auto_id }}" class="form-control" placeholder="Repeat the password" required> 
            </div>

            <button type="submit" class="btn btn-primary">Signup</button>

        </form>
        


    </div>


{% endblock %}